### ISSUE TITLE
docker run - not working locally

### ISSUE THREAD

**Issue by j450h1** [GoogleCloudPlatform/datalab#725]
I'm trying to run this locally.

When I run:
`docker run -i -t datalab -p 8081:8081 -v local_directory:/content`
Unable to find image 'datalab:latest' locally
Pulling repository docker.io/library/datalab
Error: image library/datalab:latest not found

Then I ran:
`docker images' and got this result
REPOSITORY                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
gcr.io/cloud_datalab/datalab     latest              9eb6bb4a7ac9        2 weeks ago         1.132 GB

So I modified original like so:
`docker run -i -t gcr.io/cloud_datalab/datalab  -p 8081:8081 -v local_directory:/content`

Then I got this error:

creating master branch
Initialized empty Git repository in /master_branch/.git/

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@ee44ce758762.(none)')
error: src refspec master does not match any.
error: failed to push some refs to 'https://source.developers.google.com/p//'
failed creating master branch*

Any help would be appreciated. Thanks!

**Comment by qimingj** [comment]
We can run Datalab either locally or in cloud. The image gcr.io/cloud_datalab/datalab assumes it is running on a Google AppEngine VM, and it relies on some environment variables specific in that environment. See https://github.com/GoogleCloudPlatform/datalab/blob/master/containers/datalab/content/setup-env.sh.

If you want to try local run, take a look at https://github.com/GoogleCloudPlatform/datalab/wiki/Build-and-Run. You should be able to build the docker image yourself and run it locally, with all the required environment variables set up for you.

**Comment by j450h1** [comment]
Thanks. I'm making some progress now. I cloned repo locally, ran all the commands up until this:

`jass-air:datalab jas$ cd sources && ./build.sh
Building lib/api ... 
succeeded

Building lib/datalab ... 
succeeded

Building tools ... 
succeeded

Building web ... 
failed
Build aborted.`

Was getting excited but the web failed. Any advice would be appreciated.

**Comment by nikhilk** [comment]
If you build from within the web directory, it will likely tell you more specific details on the build error.

Also, look at run.sh in the containers/datalab directory. There are a few flags that run.sh passes to datalab that are interesting to have it operate in local mode instead of in cloud mode.

Hope that gets you unblocked.

**Comment by j450h1** [comment]
Thanks for quick response. Tried that too. No luck yet:

**jass-air:web jas$ ls**
build.sh	datalab
**jass-air:web jas$ ./build.sh**
datalab/jupyter.ts(89,27): error TS1121: Octal literals are not allowed in strict mode.
datalab/server.ts(28,8): error TS1214: Identifier expected. 'static' is a reserved word in strict mode. Modules are automatically in strict mode.
datalab/server.ts(240,19): error TS1214: Identifier expected. 'static' is a reserved word in strict mode. Modules are automatically in strict mode.
jass-air:web jas$ 

Any other suggestions. I'm opening terminal using docker Quickstart Terminal. Looks like boot2docker is deprecated.

**Comment by nikhilk** [comment]
You're hitting a build error because of a change in a newer TypeScript compiler. We need to make changes in our code to account for that.

If you're keen to get unblocked, you could include the changes from https://github.com/GoogleCloudPlatform/datalab/pull/588/files locally and see if it gets you further.

However, I personally recommend running the existing container rather than build the latest... See my comment earlier about run.sh (it changes the entrypoint command to run in local mode as opposed to cloud mode).

**Comment by j450h1** [comment]
Thats okay Nikhil. I will wait for a more stable build.

**Comment by gramster** [comment]
This should be much better now. Follow the Getting Started page on the wiki.

**Comment by j450h1** [comment]
Great job guys! I was able to set it up and access it locally now.
