### ISSUE TITLE
Surface workspace sync error to the user

### ISSUE THREAD

**Issue by Di-Ku** [GoogleCloudPlatform/datalab#752]
(Based on conversation with Bradley related to a customer-reported issue)
Currently workspace sync failure (after retries) is logged but not surfaced to the user. This can lead to data loss in some cases. Such failures should be surfaced in the UI to the user while the VM is up and there is a way to retrieve the files.

**Comment by qimingj** [comment]
Investigation so far:

1. From logs, there were wsync errors but it seems we recovered.
2. The issue seems not happening now. Customer created a new notebook and it appeared in source repository as uncommitted changes.
3. It seems customer's workspace history is still there. Checking with customer on whether the history includes their "missing" notebooks.

**Comment by gramster** [comment]
Close as obsolete?

**Comment by qimingj** [comment]
Yep.
